ibm-openbmc/openpower-hw-isolation

- org.open_power.HardwareIsolation.service
Add a dependency to the org.open_power.HardwareIsolation service file to
start after the openpower-update-bios-attr-table service, which is the
one that sets up the GUARD file by reading a json file to determine the
lid number that corresponds to the GUARD file in that particular system,
then it sets a bios attribute so that PLDM can read all the files.
Tested: Verified that hw isolation started successfully:
Nov 03 15:12:22 localhost systemd[1]: Starting Phosphor PLDM Daemon...
Nov 03 15:12:22 localhost systemd[1]: Started Phosphor PLDM Daemon.
Nov 03 15:12:28 localhost systemd[1]:
openpower-process-host-firmware.service: Deactivated successfully.
Nov 03 15:12:28 localhost systemd[1]:
openpower-update-bios-attr-table.service: Deactivated successfully.
Nov 03 15:12:28 localhost …
> org.open_power.HardwareIsolation: Add dependency

- src/hw_isolation_record/manager.cpp
Currently, the hardware isolation record D-bus entries are not cleared
if someone cleared (aka reset) all the records by using the "guard -r"
so fixes that issue in this patch.
Tested:
- Without fix.
```
root@rain98bmc:~# guard -c physical:sys-0/node-0/dimm-0
root@rain98bmc:~# guard -l
ID       | ERROR    |  Type  | Path
00000001 | 00000000 | manual | physical:sys-0/node-0/dimm-0
root@rain98bmc:~# busctl tree org.open_power.HardwareIsolation
└─/xyz
└─/xyz/openbmc_project
└─/xyz/openbmc_project/hardware_isolation
└─/xyz/openbmc_project/hardware_isolation/entry
└─/xyz/openbmc_project/hardware_isolation/entry/1
root@rain98bmc:~# guard -r
root@rain98bmc:~# guard -l
No Records to display
root@rain98bmc:~# busctl tree org.open_power.HardwareIsolation
└─/xyz
└─/xyz/openbmc_project …
```
> record: manager: Fix: Clear entries if no record

- include/common/isolatable_hardwares.hpp
- src/common/isolatable_hardwares.cpp
Please review the last 4 patches since the remaining patches are added for different purposes and these patches included in the separate PR https://github.com/ibm-openbmc/openpower-hw-isolation/pull/10
> Add Generic_I2C_Device, PMIC, and OSCREFCLK targets

- src/hw_isolation_record/manager.cpp
- libguard introduced a new type record called "GARD_Sticky_deconfig"
because BMC and host application need to support the resource
recovery feature during the boot of the host.
- The openpower-hw-isolation application should not display
the GARD_Sticky_deconfig record like GARD_Reconfig records so
added the support for the same.
> record: Don't create entries for the GARD_Sticky_deconfig record

- include/hw_isolation_record/manager.hpp
- src/hw_isolation_record/manager.cpp
- The libguard is changed to support overriding the hardware isolation
record into their persisted location.
- Override the Manual hardware isolation record by either Critical
or Warning failures.
- Override the Warning hardware isolation record by Critical
failure.
- So, added the same support in the openpower-hw-isolation application
to update the D-Bus entries.
Tested:
- Verified by creating the manual and critical isolation record on
the same hardware.
- Verified by creating the manual and warning isolation record on
the same hardware.
- Verified by creating the warning and critical isolation record on
the same hardware.
> record: Update the hardware isolation D-Bus entries if overridden

- include/hw_isolation_record/entry.hpp
- src/hw_isolation_event/hw_status_manager.cpp
- src/hw_isolation_record/entry.cpp
- src/hw_isolation_record/manager.cpp
It fixes [SW541617](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW541617)
**Background:** 
- Currently, the hardware inventory "Enabled" D-Bus property showing as
"false" even if it is functional and doesn't have hardware isolation
record or the existing hardware isolation record resolved for the
respective hardware inventory object.
- So, updated the hardware inventory "Enabled" D-Bus property as "true"
if the above case occurs.
**Tested:**
- Verified the "Enabled" property during cold boot without hardware
isolation record.
- Verified the "Enabled" property by manually resolving hardware
isolation record.
> Fix, Update hardware inventory "Enabled" D-Bus property

- include/common/utils.hpp
- src/common/utils.cpp
- src/hw_isolation_record/entry.cpp
- src/hw_isolation_record/manager.cpp
- src/hw_isolation_record/openpower_guard_interface.cpp
- The hardware isolation D-bus request might be triggered by the application
that might act as an external user interface like a redfish server so
the redfish server need to return the appropriate error to the end
user if the end-user request failed.
- Currently, the hardware isolation returning "NotAllowed" error in the
below cases but, the user might need to take some action based on the
error.
- Returns "NotAllowed" error when the manual hardware isolation request
is not allowed during host power on or running.
- Returns "NotAllowed" error when the hardware isolation service is disabled
by using the "allow_hw_isolation" settings.
- Returns "NotAllowed" error when the hardware isolation record file is full.
- Fixing the above case by returning a different error.
- Returns "NotAllowed" …
> record: Return an appropriate error if the D-Bus request failed

- src/hw_isolation_record/entry.cpp
- src/hw_isolation_record/manager.cpp
- We should not allow the user to delete the system isolated hw entry
because that might be created by the system due to some hardware error.
- If we are allowed to clear that entry then, the system might hit
the same error until the hardware is replaced.
- So, restricted the user to delete the system isolated hw entry
in the patch.
- Note, The openpower-hw-isolation still allows the system isolated
hardware entries to clear if the user tried through "DeleteAll".
Tested:
- Verified by clearing the system isolated hardware entry through D-Bus.
```
> guard -l
ID       | ERROR    |  Type  | Path
00000001 | 50000425 | fatal | physical:sys-0/node-0/dimm-0
> busctl call org.open_power.HardwareIsolation /xyz/openbmc_project/ \
hardware_isolation/entry/1 xyz.openbmc_project.Object.Delete Delete …
```
> record: Don't allow the user to delete the system isolated hw entry

- include/common/isolatable_hardwares.hpp
- include/common/utils.hpp
- include/hw_isolation_event/hw_status_manager.hpp
- src/common/isolatable_hardwares.cpp
- src/common/utils.cpp
- src/hardware_isolation_main.cpp
- src/hw_isolation_event/hw_status_manager.cpp
- In the OpenPOWER based system, the Core can be deallocated at the runtime
by creating the hardware isolation record.
- If the Core is deallocated then, we need to communicate this information
to the end-user whenever the user tried to get a core state.
- So, The openpower-hw-isolation application will start watcher once the host
reached to runtime (OSRunning) to monitor the Functional property value
change for all present cores in the inventory.
- Once the core is deallocated in the host side, the host will send the PLDM
sensor event to the BMC that will update in the core inventory Functional
property, now the watcher will wake and look for the respective core
hardware isolation record and create an event that will be translated into
the Redfish Status.Condition property when the user …
> event: Create an event if the core is deallocated at the runtime

- include/hw_isolation_record/manager.hpp
- src/hardware_isolation_main.cpp
- src/hw_isolation_record/manager.cpp
- Currently, the openpower-hw-isolation application using the sleep
call to solve the atomicity on hardware isolation record partition
file if the file is updated by the host application.
- The openpower-hw-isolation application acting as a D-Bus service
daemon to process the implemented D-Bus request but due to the sleep
call the openpower-hw-isolation application halted so, it was not able
to process the D-Bus request until the sleep call returns.
- So, fixing this by using the timer event source i.e, the timer object
will be created whenever the inotify event is received, once the timer
is expired, remove timer and process hardware isolation records from
the partition file.
Tested:
- Verified by sending more than one request at the same time.
> record: Use timer event source instead of sleep call

- service_files/org.open_power.HardwareIsolation.service
- Recently, we added a code to check the host state to create the watcher
if the OS is running to get to know whether the core is deallocated at
the runtime or not, and that watcher is used to create the event
to represent the state of the core in the Redfish side.
- That check is also added in the restore path to create the watcher
if the BMC reboots and the OS is running.
- In the certain system the Host state service took some time to start but,
the HardwareIsolation service started and attempted to get the host
state but, that's failed due to the Host service did not start.
- So, fixed that by adding "After" and "Wants" with Host state service.
Tested:
```
Apr 06 07:33:22 raingdl8 systemd[1]: Starting Phosphor Host State Manager...
...
Apr 06 07:33:27 raingdl8 systemd[1]: Started …
```
> service: Start HardwareIsolation after the Host state started

- meson_options.txt
- The pnor directories are being replaced with the hostfw directories
that are handled by PLDM.
> meson_options: Update DEVTREE path

- service_files/org.open_power.HardwareIsolation.service
- In the OpenBMC project there is an anti-pattern that says we should not
launch the application with the "env".
- Refer to the below link to get more details
https://github.com/openbmc/docs/blob/master/anti-patterns.md#use-of-usrbinenv-in-systemd-service-files
> service: Don't launch the application with "env"

- service_files/org.open_power.HardwareIsolation.service
It fixes [SW549944](https://w3.rchland.ibm.com/projects/bestquest/?defect=SW549944) - Created an MFT and it is in the review for the approval.
- The "phal-reinit-devtree" service will be called as part of the
host cold boot path to reinit the PHAL device tree with read-only
version device tree and preserve attributes if any into read-write
version device tree.
- The HardwareIsolation service will be called as part of the BMC
boot path.
- Recently, we noticed that the host trying to boot before the BMC
raches to standby (aka Ready) state i.e the BMC and Host trying
to boot parallel due to the external or internal request and that
is not expected but, we cannot control that on a certain path
(for example, in-band code update path).
- So, whenever the Host trying to boot before the BMC …
> service: Start HardwareIsolation before Reinit PHAL DEVTREE

- include/hw_isolation_record/entry.hpp
- src/hw_isolation_record/manager.cpp
- Recently, the libguard "EntityPath" structure constructor was updated to get the data buffer length so it is fixed in this patch to avoid a compilation error.
> Use updated EntityPath constructor

- src/common/utils.cpp
- src/hw_isolation_record/manager.cpp
When an error is injected onto a core at runtime system checkstops guards the core and creates an hw-isolation entry
hw-isolation as part of creating isolation entry sets the enabled property of the core D-Bus object hosted by PLDM.
In a rare window, PLDM hangs during checkstop and recovers back. If any request comes to enable the D-Bus property of the core D-Bus object hosted by PLDM in this window the same will not be honored.
As D-Bus setProperty method fails current implementation creates the isolation entry but not the guard record.
The customer would fail to see a guard record due to checkstop and in absence of a guard record, the subsequent boots would try to boot the bad core (which should have guarded in the first place)
In the future when core D-Bus objects will be hosted by …
> record: fix guard record not created during checkstop

- README.md
- src/common/utils.cpp
Upstream added support for multi-host designs. That is, there could be
multiple host instances supported by one BMC. To do that, they instanced
the xyz.openbmc_project.State.Host service (so there is now a 0,1,2,...
added to the end of the service name.
To support backwards compatibility they have the host instance 0 service
also host the old xyz.openbmc_project.State.Host service name. This
means that one application is hosting both the
xyz.openbmc_project.State.Host and xyz.openbmc_project.State.Host0
service name. Either will work, but code needs to handle getting back 2
service names.
If IBM some day supports this multiple instance concept, then this code
will need a refactor. For now, since IBM only supports the one host
instance, put an exception in the rules to allow for the …
> 1050 fixes

- meson.build
- src/faultlog/deconfig_reason.cpp
- src/faultlog/deconfig_reason.hpp
- src/faultlog/deconfig_records.cpp
- src/faultlog/deconfig_records.hpp
- src/faultlog/faultlog_main.cpp
- src/faultlog/faultlog_policy.cpp
- src/faultlog/faultlog_policy.hpp
- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/guard_with_eid_records.hpp
- src/faultlog/guard_without_eid_records.cpp
- src/faultlog/guard_without_eid_records.hpp
- src/faultlog/meson.build
- src/faultlog/service/faultlog_bmcboot.service.in
- src/faultlog/service/faultlog_hostpoweron.service.in
- src/faultlog/service/faultlog_periodic.timer
- src/faultlog/service/meson.build
- src/faultlog/unresolved_pels.cpp
- src/faultlog/unresolved_pels.hpp
- src/faultlog/util.cpp
- src/faultlog/util.hpp
- src/meson.build
Capture isolated/deconfigured/filedcodeoverride targets in JSON file, so that the records can be generated periodically or during poweron/reipl/failure to remind the customers or service engineers about the presence of failed parts in the system.
In certain situations, the service engineer or customer can defer the service action for some of the failures. In such cases,
there are chances to miss such failure records, and the system may fail unexpectedly, causing undesirable impacts. 
This problem is overcome by sending periodic error events to remind about the failed parts present in the system.
A new type of BMC dump will be added to capture failure data in JSON file and add to the dump.
This dump will be invoked during Power on, after repair and verify or periodically once a month, …
> Capture isolated/deconfigured/fco records in JSON file

- src/faultlog/service/faultlog_hostpoweron.service.in
Upstream yocto introduced a change via e510222 (systemd-systemctl: fix instance template WantedBy symlink construction).
This fixes a bug that we in OpenBMC had been taking advantage of in that we were able to document our templated target dependencies without it actually doing anything. The real installation of services within targets occurs in our bitbake recipes due to the complexity of chassis and host instances on a per machine basis.
Leave the dependency information in the service files but comment them out. It's useful to be able to look at a service and understand which targets it's going to be installed into by the bitbake recipes.
In some cases, we had hard coded the target instance, which does install the service correctly, but only in that one target. All services should be …
> systemd: no installation in templated targets

- src/faultlog/service/faultlog_hostpoweron.service.in
As host poweron service waits for host to reach runtime, it cannot be a oneshot service, changed service type to simple.
Change-Id: I6d49178e3b35656cd4a00459eaeac6df68dd2b91
> nag: change hostpoweron service to type simple

- src/faultlog/deconfig_records.cpp
- src/faultlog/deconfig_records.hpp
- src/faultlog/faultlog_main.cpp
- src/faultlog/faultlog_policy.cpp
- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/guard_without_eid_records.cpp
- src/faultlog/unresolved_pels.cpp
- src/faultlog/util.cpp
Fix some of the issues noticed related to traces, and formatting, noticed during self-test
1) Validate pdbg target properties before accessing them
2) Use SdBusErrror exception class for any errors thrown as part of D-Bus calls.
3) Consistently log PLID in hexa decimal format
4) If PEL's are deleted for a guard record created with error injection add what ever data available rather than ignoring the guard record.
Change-Id: I081221b85f34638a77817c8b3e10a2cc37d0ec76
> nag : fix issues noticed during self test and defects

- src/faultlog/faultlog_main.cpp
- src/faultlog/meson.build
- src/faultlog/unresolved_pels.cpp
During BMC reboot with host in running state noticed guard records are not captured as part of the faultlog JSON file.
Found during BMC reboot when host is at runing pdbg device tree is not initialized so was not able to read the properties of the guarded targets.
Current error:
Jul 03 08:40:21 rain104bmc faultlog[822]: Failed to get physical path for record 1
Tested:
Jul 03 10:20:29 rain104bmc systemd[1]: Started Faultlog application. Jul 03 10:20:29 rain104bmc faultlog[2437]: faultlog app to collect deconfig/guard records details Jul 03 10:20:30 rain104bmc faultlog[2437]: faultlog GUARD_COUNT: 1, MAN_GUARD_COUNT: 1, DECONFIG_REC_COUNT: 0 , PEL_COUNT: 0
> nag : fix faultlog defects

- src/faultlog/guard_without_eid_records.cpp
For manually deconfigured records set the value to 0x0
Tested
before
{
"DECONFIGURED": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C15",
"PHYS_PATH": "physical:sys-0/node-0/proc-1",
"PLID": "0xff01",
"REASON_DESCRIPTION": "manual",
"TYPE": "Processor Module"
}
}
after
{
"DECONFIGURED": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C15",
"PHYS_PATH": "physical:sys-0/node-0/proc-1",
"PLID": 0,
"REASON_DESCRIPTION": "manual",
"TYPE": "Processor Module"
}
}
Signed-off-by: Gopichand Paturi  <gopichandpaturi@gmail.com>
Change-Id: If90887fda605e6475890807f72ac43681ea7f407
> nag: Fix PLID of deconfig records showing incorrect value

- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/unresolved_pels.cpp
nag: Rename "ERR_PLID" to "PLID" to maintain consistency
Under CEC ERROR LOG, Error Log Id is denoted as ERR_PLID and other places it is denoted as PLID. To maintain 
consistency it is renamed to "PLID"
Before:
"CEC_ERROR_LOG": [
{
"Callout Section": {},
"DATE_TIME": "07/25/2023 06:23:21",
"ERR_PLID": "0x0", ---> Not consistent
"SRC": "BD60280E"
},
Test Results:
"CEC_ERROR_LOG": [
{
"Callout Section": {},
"DATE_TIME": "07/25/2023 06:44:41",
"PLID": "0x50000d86", ---> updated to PLID
"SRC": "BD60280E"
},
Signed-off-by: Parasa Swetha <Parasa.Swetha1@ibm.com>
Change-Id: Ide71b8d0587eca212a982200d021300b3bb4ee24
> nag: Rename "ERR_PLID" to "PLID" to maintain consistency

- src/faultlog/faultlog_main.cpp
- src/faultlog/service/faultlog_periodic.service.in
- src/faultlog/util.cpp
Now periodic service is invoked as part of the initial systemd services.
As guard, device tree are not initialized yet faultlog application fails during startup.
Now modifid to exit early if in case the host is not in running state yet before checking for guard records and e.t.c.
Also adding condition path check on device tree and guard mount path to exit early if in case the service is executed before the device tree and guard are mounted.
Tested:
root@p10bmc:~# systemctl status faultlog_periodic.service
* faultlog_periodic.service - Faultlog application (periodic) Loaded: loaded (/lib/systemd/system/faultlog_periodic.service; static) Active: inactive (dead) TriggeredBy: * faultlog_periodic.timer
Condition: start condition failed at Mon 2023-07-31 01:10:03 UTC; 2min 15s ago `- …
> nag : fix periodic service fail during boot

- src/faultlog/deconfig_records.cpp
- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/guard_without_eid_records.cpp
- src/faultlog/meson.build
- src/faultlog/unresolved_pels.cpp
Now using PHAL api which fetches LOCATOIN_CODE from parent if not found in the target.
Tested:
Before
{
"MANUAL_ISOLATION": {
"CURRENT_STATE": "DECONFIGURED",
"PHYS_PATH": "physical:sys-0/node-0/proc-3/mc-3/mi-0/mcc-0/omi-1",
"REASON_DESCRIPTION": "manual",
"TYPE": "POWER10 omi"
}
}
After
{
"DECONFIGURED": {
"CURRENT_STATE": "DECONFIGURED",
"LOCATION_CODE": "Ufcs-P0-C24",
"PHYS_PATH": "physical:sys-0/node-0/proc-3/mc-3/mi-0/mcc-1/omi-1",
"PLID": "0x90000cd1",
"REASON_DESCRIPTION": "ERROR LOG",
"TYPE": "POWER10 omi"
}
}
Change-Id: I46b81ffde394ae51528617f7145a7bbbd9226a3b
> nag: get location code from parent if not found in target

- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/unresolved_pels.cpp
The spelling of "Guard" has been written as "GARD" instead of "GUARD" in some places. Therefore, to maintain consistency, "GARD_RECORD" has been changed to "GUARD_RECORD"
Before:
"SERVICEABLE_EVENT": {
"CEC_ERROR_LOG": [
{
"Callout Section": {
"Callout Count": 2,
"Callouts": [
{
"CCIN": "5C67",
"Location Code": "U78DA.ND0.WZS004A-P0-C24",
"Part Number": "F210110",
"Priority": "Medium",
"Serial Number": ""
},
{
"2. Priority": "Medium",
"Procedure": "BMC0004"
}
]
},
"DATE_TIME": "09/27/2023 16:30:16",
"PLID": "0x5000ff31",
"SRC": "BD503001"
},
{
"RESOURCE_ACTIONS": {
"CURRENT_STATE": "DECONFIGURED",
"GARD_RECORD": true,                        --> misspelt
"REASON_DESCRIPTION": "PREDICTIVE",
"TYPE": "Processor Module"
}
}
]
}
Test Results:
"SERVICEABLE_EVENT": {
"CEC_ERROR_LOG": [
{
"Callout …
> nag: Rename 'GARD_RECORD' to 'GUARD_RECORD'

- src/faultlog/faultlog_main.cpp
Even without guard records and pels, SERVICEABLE_EVENT is displayed in faultlog. Removing the SERVICEABLE_EVENT section if there is no data in it.
Before:
```
root@p10bmc:/tmp# guard -l
No Records to display
root@p10bmc:/tmp# peltool -l
{}
root@p10bmc:/tmp# faultlog -f
<6> faultlog app to collect deconfig/guard records details <6> Latest chassis poweron time read is :12/06/2023 06:39:33 [
{
"SYSTEM": {
"SYSTEM_TYPE": "9105-22B"
}
},
{
"POLICY": {
"FCO_VALUE": 0,
"MASTER": true,
"PREDICTIVE": true
}
},
{
"SERVICEABLE_EVENT": []  ----> It is displayed even if it is empty
}
]
root@p10bmc:/tmp# faultlog -u
<6> faultlog app to collect deconfig/guard records details <6> Latest chassis poweron time read is :12/06/2023 06:39:33 [
{
"SYSTEM": {
"SYSTEM_TYPE": "9105-22B"
}
},
{
"SERVICEABLE_EVENT": …
```
> Remove SERVICEABLE_EVENT section if it is empty

- src/faultlog/guard_with_eid_records.cpp
- src/faultlog/unresolved_pels.cpp
Before:
```
"SERVICEABLE_EVENT": [
{
"CEC_ERROR_LOG": [
{
"Callout Section": {},
"DATE_TIME": "12/19/2023 10:34:13",
"PLID": "0x500011a4",
"SRC": "BD60280E"
},
{
"RESOURCE_ACTIONS": {
"CURRENT_STATE": "DECONFIGURED",
"GUARD_RECORD": true,
"REASON_DESCRIPTION": "PREDICTIVE",
"TYPE": "POWER10 DIMM"
}
}
]
}
]
```
Test Results:
```
"SERVICEABLE_EVENT": [
{
"CEC_ERROR_LOG": [
{
"Callout Section": {},
"DATE_TIME": "12/19/2023 10:34:13",
"PLID": "0x500011a4",
"SRC": "BD60280E"
},
{
"RESOURCE_ACTIONS": {
"CURRENT_STATE": "DECONFIGURED",
"GUARD_RECORD": true,
"PHYS_PATH": "physical:sys-0/node-0/dimm-34",             -----> Added PHYS_PATH field to RESOURCE_ACTIONS
"REASON_DESCRIPTION": "PREDICTIVE",
"TYPE": "POWER10 DIMM"
}
}
]
}
]
```
Change-Id: I8f8527d0d434fee60e132417c8c2d5bd68fbe736 …
> nag: Add Physical Path of the target to Resource Actions section

- src/faultlog/service/faultlog_create_chassis_poweron_time.service.in
Existing faultlog chassis poweron timer systemd service writes the current time to a file and exits the service.
Expectation is that the faultlog chassis poweron systemd service is restarted only during chassis poweron.
Faultlog chassis poweron systemd service has a dependency on obmc poweron target.
Noticed during warm reboot all targets that have dependency and not running on obmc poweron target are started. As the faultlog timer service has exited it restarts it and it writes new time stamp to the file.
Application considers only those PELS that are created after the new chassis poweron time and missed PELS that caused reipl/warm reboot.
Now modified to let the service run till the chassis poweroff service is called.
Tested
Before:
Oct 16 04:42:51 rainjmt01bmc …
> nag: fix service file to remain after exit during warm reboot

- src/common/isolatable_hardwares.cpp
This reverts commit 8b8286d81692b364da24334011388a40e0c2911a.
Location Code for OCMB is same as DIMM on rainier and everest, so we decided to fetch it from OCMB target as it is available in device tree. But the Location Code seems to be different for OCMB and DIMM on bonnell, so reverting this commit as it is causing some parent DIMM numbering issues on bonnell.
> Revert "common: Consider ocmb as parent target instead of dimm"

- src/common/isolatable_hardwares.cpp
Previously, there was only one DIMM under OCMB. Now, we have two DIMMs
under one OCMB. Therefore, in the case of multiple DIMMs, we consider
the last DIMM as the parent for OCMB. This approach resolves DIMM
numbering issues on Bonnell, as considering OCMB as the parent was
causing discrepancies.
Test  Results:
Before:
Dimm numbers were same for both ocmbs.
```
root@p10bmc:/tmp# guard -l
ID         | ERROR      | Type     | Path
0x00000001 | 0x50004cce | fatal    | physical:sys-0/node-0/ocmb_chip-4
0x00000002 | 0x50004cce | fatal    | physical:sys-0/node-0/ocmb_chip-5
swetha@IBM-PF3XHYG0:~$ curl -k -H "X-Auth-Token: $bmc_token" -X GET
https://${bmc}/redfish/v1/Systems/system/LogServices/HardwareIsolation
/Entries
{
"@odata.id": "/redfish/v1/Systems/system/LogServices/HardwareIsolation …
```
> common: Consider the last dimm as parent

- src/faultlog/unresolved_pels.cpp
Faultlog application checks if deconfigured property is set to true in a PEL.
But there can be PELs which have the deconfigured
property set, but with hidden property also set,
in which case such PELs should not be considered for nag dump.
Whenever Hidden property is set in a PEL, faultlog is expected to ignore such a PEL.
Tested:
Recreated the error scenario with corrupted image side switch with PEL generated having deconfigured and hidden bits set to true.Verified that faultlog is no longer picking up the above PEL for a callout.
Before:
[
{
"SYSTEM": {
"SYSTEM_TYPE": "9105-22A"
}
},
{
"SERVICEABLE_EVENT": [
{
"CEC_ERROR_LOG": [
{
"Callout Section": {
"Callout Count": 2,
"Callouts": [
{
"1. Priority": "High",
"Procedure": "HB00055"
},
{
"CCIN": "32A1",
"Location Code": …
> nag: Ignore PELs with hidden property set to true

- src/faultlog/unresolved_pels.cpp
```
nag: Ignore PELs with hidden property set to true```
> 1050: Merge pull request #90 from gcpin/main

- src/faultlog/unresolved_pels.cpp
Faultlog application checks if deconfigured property is set to true in a PEL.
But there can be PELs which have the deconfigured
property set, but with hidden property also set,
in which case such PELs should not be considered for nag dump.
Whenever Hidden property is set in a PEL, faultlog is expected to ignore such a PEL.
Tested:
With PELs having deconfigured and hidden parameters set in a system, attempted to create fault log PEL and validated that the faultlog PEL is not getting created as PEL count is zero as the faultlog app is ignoring the PELs with hidden bit set.
Before:
bmc:~# faultlog -c
faultlog app to collect deconfig/guard records details Latest chassis poweron time read is :05/22/2024 09:34:39 faultlog GUARD_COUNT: 0, MAN_GUARD_COUNT: 37,
DECONFIG_REC_COUNT: 77 , PEL_COUNT: …
> nag: Ignore PELs if hidden property is set.

- src/faultlog/unresolved_pels.cpp
```
nag: Ignore PELs if hidden property is set.```
> 1050: Merge pull request #94 from gcpin/568085

- include/hw_isolation_record/manager.hpp
- include/hw_isolation_record/openpower_guard_interface.hpp
- src/hw_isolation_record/manager.cpp
- src/hw_isolation_record/openpower_guard_interface.cpp
Calling invalidateAll method of libguard instead of invalidating one by
one to support retention of core guard records and clear all other
records. This also supports clearing a single guard record (including core).
This change will cause the object paths to be deleted after deletion of all the guard records. So there might be a delay of 5-10 sec in clearing the object paths.
Change-Id: Ie0ff94ede36f39a98417be4f8b293d90495efd41
Signed-off-by: SwethaParasa <parasa.swetha1@ibm.com>
> record: Spare core support

- src/faultlog/faultlog_main.cpp
As system serial number is used to determine the faulty system by the product engineers adding System serial number for the faultlog json file
faultlog json file captures all the garded, deconfigured hardware elements in JSON file which are used by the PE.
Fixes: 647272
Change-Id: I7b9fad41e6d8aab91c28454681938fcc790e9108
> faultlog - add system serial number to the faultlog JSON file

- src/faultlog/guard_with_eid_records.cpp
Do not notify the caller if there are only spare core guard records, but collect
spare core gard reocrd details if there are other gard records or unresolved PELS.
Do not create a DeconfiguredHw PEL if there are only spare core gard records.
DeconfiguredHW PEL is created if the gard record count or unresloved PEL's count
is greater than zero. So change is made to not to consider spare core gard record
as part of calculating the gard record count.
HMC monitors DeconfiguredHw and initiates NAGDUMP.
Change-Id: I94419ab8f7343daf182c6a141b46d60608d8807e
> faultlog - cater for spare core gard records

- src/faultlog/util.cpp
Due to some parsing error some stray characters are added to the callout section in the faultlog.json file
Now modified to use regular expression rather than "C" way of parsing.
Example: callout number 3. is added to the Priority key value Before:
"Callouts": [
{
"3. Priority": "Medium",
"Part Number": "PWRSPLY"
}
After:
"Callouts": [
{
"Priority": "Medium"
"Part Number": "PWRSPLY",
}
Change-Id: Iea8b62e018db4a6f0cae069976bedc88abe7e2c5
> faultlog : fix parser for callout data read from PEL

- meson.build
- tools/create_pel.cpp
- tools/create_pel.hpp
- tools/meson.build
- tools/systemguard.cpp
Test Results:
```
root@p10bmc:/tmp/test# sysguard -c  physical:sys-0/node-0/dimm-0 -s
critical
Creating System guard of type critical on the target with physical path physical:sys-0/node-0/dimm-0
root@p10bmc:/tmp/test# guard -l
ID         | ERROR      | Type           | Path
0x00000001 | 0x5000000d | fatal          | physical:sys-0/node-0/dimm-0
Nov 21 11:19:12 p10bmc phosphor-log-manager[398]: GUARD: (23 01 00 02 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ) Nov 21 11:19:12 p10bmc phosphor-log-manager[398]: Created PEL 0x5000000d (BMC ID 14) with SRC BD8D2006
root@p10bmc:/tmp/test# sysguard -c  physical:sys-0/node-0/dimm-2 Creating System guard of type warning on the target with physical path physical:sys-0/node-0/dimm-2
root@p10bmc:/tmp/test# guard -l
ID         | ERROR      | …
```
> Develop a CLI Application for creating system guard

- include/common/utils.hpp
- src/common/utils.cpp
- src/hw_isolation_event/hw_status_manager.cpp
- src/hw_isolation_record/manager.cpp
If a system guard's associated PEL is removed, the guard was skipped to be displayed in the GUI as the association is lost. The following error was displayed.
Skipping to restore a given isolated hardware [23 01 00 02 00 03 00 ] : Due to failure to get BMC error log path by isolated hardware EID (aka PEL ID) [1342178283]
As the guard still exists, it is better to display the guard without the errorlog association. The gui could show a system guard (predictive/ fatal) without the errorlog.
Currently the PEL associated with the guard cannot be removed. This is an extra check on top of it.
Test results: Predictive guard does not have an errorlog association
```
busctl introspect org.open_power.HardwareIsolation /xyz/openbmc_project/hardware_isolation/events/hw_isolation_status/1
NAME …
```
> Remove errorlog association on PEL deletion

- include/common/watch.hpp
- src/common/watch.cpp
- src/hw_isolation_record/manager.cpp
This change addresses the issue where the GUI did not immediately reflect cleared records after `deleteall`, causing inconsistencies. It also prevents unnecessary inotify signals during `clearall` by removing the watch before clearing and re-enabling it after updating D-Bus entries. This ensures accurate D-Bus updates and a more responsive UI.
Changes part of this commit
- Ensure GUI reflects cleared records immediately after `deleteall`, instead of waiting for guard file updates. This prevents UI inconsistencies.
- Refresh D-Bus entries with the correct record count to maintain accuracy.
- Remove inotify watch before `clearall`, since it is only allowed when the host is powered off. This prevents unnecessary inotify signals from triggering.
- Re-enable inotify watch after updating all …
> Fix GUI refresh and inotify handling for deleteall/clearall
